In [1]:
import warnings
warnings.filterwarnings("ignore")

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [4]:
df_train=pd.read_csv("train.csv")
df_test=pd.read_csv("test.csv")

In [5]:
print('The Shape Of training data:',df_train.shape)
print('The Shape Of testing data:',df_test.shape)

The Shape Of training data: (891, 12)
The Shape Of testing data: (418, 11)

In [6]:
#Save the 'Id' column
train_Id = df_train['PassengerId']
PassengerId = df_test['PassengerId']

In [7]:
#Now drop the  'Id' colum since it's unnecessary for  the prediction process.
#df_train.drop("PassengerId", axis = 1, inplace = True)
#df_test.drop("PassengerId", axis = 1, inplace = True)

In [8]:
df_train["source"]="train"
df_test["source"]="test"

In [9]:
df=pd.concat([df_train,df_test])

In [11]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,source
0,1,0.0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,train
1,2,1.0,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,train
2,3,1.0,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,train
3,4,1.0,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,train
4,5,0.0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,train

In [12]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,source
413,1305,NaN,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S,test
414,1306,NaN,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C,test
415,1307,NaN,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S,test
416,1308,NaN,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S,test
417,1309,NaN,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C,test

In [13]:
df.reset_index(drop=True,inplace=True)

In [14]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,source
1304,1305,NaN,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S,test
1305,1306,NaN,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C,test
1306,1307,NaN,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S,test
1307,1308,NaN,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S,test
1308,1309,NaN,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C,test

In [15]:
df['Members'] = df['SibSp'] + df['Parch'] + 1

In [16]:
#survival:    Survival 
#PassengerId: Unique Id of a passenger. 
#pclass:    Ticket class     
#Sex:    Sex     
#Age:    Age in years     
#sibsp:    # of siblings / spouses aboard the Titanic     
#parch:    # of parents / children aboard the Titanic     
#ticket:    Ticket number     
#fare:    Passenger fare     
#cabin:    Cabin number     
#embarked:    Port of Embarkation(C = Cherbourg, Q = Queenstown, S = Southampton)

In [17]:
df[['Last_name','First_name']] = df['Name'].str.split(pat=",", n=1, expand=True)
df[['Title','First_name']] = df['First_name'].str.split(pat=".", n=1, expand=True)
df['Title'] = df['Title'].str.strip()
df['Last_name'] = df['Last_name'].str.strip()
df = df.drop('Name', axis=1)
df.head()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,source,Members,Last_name,First_name,Title
0,1,0.0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,train,2,Braund,Owen Harris,Mr
1,2,1.0,1,female,38.0,1,0,PC 17599,71.2833,C85,C,train,2,Cumings,John Bradley (Florence Briggs Thayer),Mrs
2,3,1.0,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,train,1,Heikkinen,Laina,Miss
3,4,1.0,1,female,35.0,1,0,113803,53.1000,C123,S,train,2,Futrelle,Jacques Heath (Lily May Peel),Mrs
4,5,0.0,3,male,35.0,0,0,373450,8.0500,NaN,S,train,1,Allen,William Henry,Mr

# Ticket

In [18]:
df[['Ticket']] = df['Ticket'].str.upper()

# Ticket Start with 'A'

In [19]:
df[(df.Ticket.str[0]=='A')].Ticket.value_counts()

A/4 48871      3
A/5. 851       3
A/5. 3337      2
A/5. 3336      2
A./5. 3338     1
A/4 45380      1
A/5 21174      1
A/5 2817       1
A/5. 2151      1
A./5. 3235     1
A/5 3594       1
A/4. 20589     1
AQ/4 3130      1
A/5 21173      1
A. 2. 39186    1
A/5 2466       1
A/4. 34244     1
A/5. 10482     1
A.5. 18509     1
A/5 3540       1
A/5. 13032     1
A4. 54510      1
A./5. 2152     1
A/5 3536       1
A/5 1478       1
A/4 48873      1
A/5 3902       1
A.5. 11206     1
A.5. 3236      1
A/5 21172      1
AQ/3. 30631    1
A/S 2816       1
A/5 21171      1
A/4. 39886     1
A/4 31416      1
A/5 21175      1
Name: Ticket, dtype: int64

In [20]:
df['Ticket'] = df.Ticket.str.replace('A. 2.','A/2')
df['Ticket'] = df.Ticket.str.replace('AQ/3.','AQ/3')
df['Ticket'] = df.Ticket.str.replace('A/4. 39886','A/4 39886')
df['Ticket'] = df.Ticket.str.replace('A/4. 20589','A/4 20589')
df['Ticket'] = df.Ticket.str.replace('A/4. 34244','A/4 34244')
df['Ticket'] = df.Ticket.str.replace('A4. 54510','A/4 54510')
df['Ticket'] = df.Ticket.str.replace('A./5.','A/5')
df['Ticket'] = df.Ticket.str.replace('A/5. 851','A/5 851')
df['Ticket'] = df.Ticket.str.replace('A/5. 3337','A/5 3337')
df['Ticket'] = df.Ticket.str.replace('A/5. 3336','A/5 3336')
df['Ticket'] = df.Ticket.str.replace('A/5. 2151','A/5 2151')
df['Ticket'] = df.Ticket.str.replace('A/5. 10482','A/5 10482')
df['Ticket'] = df.Ticket.str.replace('A/5. 13032','A/5 13032')
df['Ticket'] = df.Ticket.str.replace('A.5. 11206','A/5 11206')
df['Ticket'] = df.Ticket.str.replace('A.5. 18509','A/5 18509')
df['Ticket'] = df.Ticket.str.replace('A.5. 11206','A/5 11206')
df['Ticket'] = df.Ticket.str.replace('A.5. 3236','A/5 3236')

In [21]:
df[(df.Ticket.str[0]=='A')].Ticket.value_counts()

A/4 48871     3
A/5 851       3
A/5 3337      2
A/5 3336      2
A/5 10482     1
A/5 3236      1
A/4 31416     1
A/5 3594      1
A/5 2151      1
A/5 2466      1
A/5 11206     1
A/5 3540      1
A/5 18509     1
A/4 48873     1
A/5 21173     1
A/4 54510     1
A/4 34244     1
A/5 21175     1
A/5 2817      1
A/4 45380     1
A/5 2152      1
A/2 39186     1
AQ/4 3130     1
A/5 1478      1
A/5 3338      1
A/4 39886     1
A/4 20589     1
AQ/3 30631    1
A/5 3536      1
A/5 3902      1
A/5 21172     1
A/5 21174     1
A/S 2816      1
A/5 21171     1
A/5 3235      1
A/5 13032     1
Name: Ticket, dtype: int64

# Ticket Start with 'C'

In [22]:
df[(df.Ticket.str[0]=='C')].Ticket.value_counts()

CA/243              11
CA 2144              8
C.A/215              4
C.A. 34651           4
C.A. 33112           4
C 4001               3
C.A. 31921           3
C.A/273              3
C.A. 37671           3
C.A. 31029           3
C.A. 6212            2
C.A. 33595           2
CA 31352             2
C.A. 31026           1
C.A/2580             1
C.A. 34260           1
C 7077               1
C.A. 42795           1
C 17368              1
C 7075               1
C.A. 33111           1
C.A/2395             1
C.A. 30769           1
C 17369              1
C.A. 15185           1
C.A. 31030           1
CA/214               1
C 7076               1
C.A. 17248           1
C.A/2566             1
C.A. 34644           1
C.A/2579             1
C.A. 49867           1
C.A/2178             1
C.A. 5547            1
C.A./SOTON 34068     1
C.A. 34050           1
C.A. 18723           1
Name: Ticket, dtype: int64

In [23]:
df['Ticket'] = df.Ticket.str.replace('CA.','CA')
df['Ticket'] = df.Ticket.str.replace('C.A.','CA')
df['Ticket'] = df.Ticket.str.replace('CA2144','CA 2144')
df['Ticket'] = df.Ticket.str.replace('CA31352','CA 31352')
df['Ticket'] = df.Ticket.str.replace('CA243','CA 243')
df['Ticket'] = df.Ticket.str.replace('CA215','CA 215')
df['Ticket'] = df.Ticket.str.replace('CA273','CA 273')
df['Ticket'] = df.Ticket.str.replace('CA2580','CA 2580')
df['Ticket'] = df.Ticket.str.replace('CA214','CA 214')
df['Ticket'] = df.Ticket.str.replace('CA2579','CA 2579')
df['Ticket'] = df.Ticket.str.replace('CA2178','CA 2178')
df['Ticket'] = df.Ticket.str.replace('CA2395','CA 2395')
df['Ticket'] = df.Ticket.str.replace('CA2566','CA 2566')

In [24]:
df[(df.Ticket.str[0]=='C')].Ticket.value_counts()

CA 243            11
CA 2144            8
CA 215             4
CA 34651           4
CA 33112           4
CA 37671           3
CA 273             3
CA 31921           3
CA 31029           3
C 4001             3
CA 31352           2
CA 33595           2
CA 6212            2
CA 214             1
CA 17248           1
C 7075             1
CA 42795           1
C 7077             1
CA 34644           1
CA 33111           1
CA 31026           1
CA 34260           1
CA 2566            1
CA 2579            1
CA/SOTON 34068     1
CA 15185           1
CA 2580            1
C 17369            1
CA 18723           1
CA 30769           1
CA 5547            1
C 7076             1
C 17368            1
CA 31030           1
CA 49867           1
CA 34050           1
CA 2395            1
CA 2178            1
Name: Ticket, dtype: int64

# Ticket Start with 'F'

In [25]:
df[(df.Ticket.str[0]=='F')].Ticket.value_counts()

F.C.C. 13529    3
F.C. 12750      2
F.C.C. 13528    2
F.C.C. 13534    2
FA 265302       1
F.C.C. 13540    1
F.C.C. 13531    1
F.C. 12998      1
Name: Ticket, dtype: int64

In [26]:
df['Ticket'] = df.Ticket.str.replace('F.C.C.','FCC')
df['Ticket'] = df.Ticket.str.replace('F.C. 12750','FC 12750')
df['Ticket'] = df.Ticket.str.replace('F.C. 12998','FC 12998')

In [27]:
df[(df.Ticket.str[0]=='F')].Ticket.value_counts()

FCC 13529    3
FCC 13528    2
FC 12750     2
FCC 13534    2
FA 265302    1
FC 12998     1
FCC 13531    1
FCC 13540    1
Name: Ticket, dtype: int64

# Ticket Start with 'S'

In [28]:
df[(df.Ticket.str[0]=='S')].Ticket.value_counts()

S.O.C. 14879          7
SC/PARIS 2123         4
S.C./PARIS 2079       3
SOTON/O.Q. 3101315    3
S.O./P.P. 3           2
SC/PARIS 2167         2
STON/O2. 3101279      2
S.O./P.P. 2           2
SCA2037               2
SCA 3085              2
SOTON/O.Q. 3101310    1
STON/O2. 3101283      1
STON/O 2. 3101280     1
SOTON/OQ 3101317      1
SC 14888              1
SOTON/OQ 392090       1
SOTON/O.Q. 3101314    1
SW/PP 751             1
SCA3 2861             1
SCA2568               1
SOTON/O2 3101272      1
SOTON/O.Q. 3101308    1
STON/O 2. 3101291     1
SOTON/OQ 3101316      1
STON/O 2. 3101273     1
STON/O 2. 3101294     1
STON/O 2. 3101293     1
SOTON/O2 3101287      1
STON/O 2. 3101286     1
SOTON/O.Q. 392078     1
STON/O 2. 3101288     1
SOTON/O.Q. 3101262    1
S.O./P.P. 752         1
STON/O 2. 3101289     1
SC/PARIS 2148         1
STON/OQ. 369943       1
STON/O2. 3101282      1
SOTON/O.Q. 3101312    1
SC/PARIS 2146         1
SCO/W 1585            1
SOTON/O.Q. 392087     1
SC/PARIS 2163         1
SOTON/O.Q. 3101305    1
SOTON/O.Q. 3101306    1
STON/O 2. 3101274     1
SOTON/OQ 392083       1
S.O.P. 1166           1
SC/PARIS 2133         1
SC/PARIS 2149         1
STON/O2. 3101290      1
STON/O 2. 3101275     1
S.C./A.4. 23567       1
S.W./PP 752           1
SOTON/O.Q. 3101309    1
STON/O 2. 3101269     1
SC/PARIS 2166         1
STON/O2. 3101271      1
SC 1748               1
SC/PARIS 2159         1
S.O./P.P. 751         1
STON/O 2. 3101292     1
STON/O 2. 3101268     1
STON/O 2. 3101285     1
SC/PARIS 2168         1
SCA BASLE 541         1
SO/C 14885            1
SC/PARIS 2147         1
SC/PARIS 2131         1
S.O./P.P. 251         1
SOTON/O.Q. 3101311    1
SOTON/OQ 392086       1
SOTON/OQ 392089       1
STON/O2. 3101270      1
SOTON/OQ 392076       1
SOTON/OQ 392082       1
SOTON/O.Q. 3101307    1
SOTON/O.Q. 3101263    1
S.P. 3464             1
SOTON/O2 3101284      1
Name: Ticket, dtype: int64

In [29]:
df['Ticket'] = df.Ticket.str.replace('S.O.C.','SOC')
df['Ticket'] = df.Ticket.str.replace('S.C./PARIS','SC/PARIS')
df['Ticket'] = df.Ticket.str.replace('SOTON/O.Q.','SOTON/OQ')
df['Ticket'] = df.Ticket.str.replace('S.O./P.P.','SO/PP')
df['Ticket'] = df.Ticket.str.replace('STON/O 2.','STON/O2')
df['Ticket'] = df.Ticket.str.replace('STON/OQ.','STON/OQ')
df['Ticket'] = df.Ticket.str.replace('STON/O2.','STON/O2')
df['Ticket'] = df.Ticket.str.replace('S.P.','SP')
df['Ticket'] = df.Ticket.str.replace('S.O.P.','SOP')
df['Ticket'] = df.Ticket.str.replace('S.C./A.4.','SC/A4')
df['Ticket'] = df.Ticket.str.replace('S.W./PP','SW/PP')
df['Ticket'] = df.Ticket.str.replace('STON/O23101273','STON/O2 3101273')
df['Ticket'] = df.Ticket.str.replace('STON/O23101275','STON/O2 3101275')
df['Ticket'] = df.Ticket.str.replace('STON/O23101292','STON/O2 3101292')
df['Ticket'] = df.Ticket.str.replace('STON/O23101289','STON/O2 3101289')
df['Ticket'] = df.Ticket.str.replace('STON/O23101274','STON/O2 3101274')
df['Ticket'] = df.Ticket.str.replace('STON/O23101268','STON/O2 3101268')
df['Ticket'] = df.Ticket.str.replace('STON/O23101285','STON/O2 3101285')
df['Ticket'] = df.Ticket.str.replace('STON/O23101269','STON/O2 3101269')
df['Ticket'] = df.Ticket.str.replace('STON/O23101286','STON/O2 3101286')
df['Ticket'] = df.Ticket.str.replace('STON/O23101293','STON/O2 3101293')
df['Ticket'] = df.Ticket.str.replace('STON/O23101291','STON/O2 3101291')
df['Ticket'] = df.Ticket.str.replace('STON/O23101288','STON/O2 3101288')
df['Ticket'] = df.Ticket.str.replace('STON/O23101294','STON/O2 3101294')
df['Ticket'] = df.Ticket.str.replace('STON/O23101280','STON/O2 3101280')
df['Ticket'] = df.Ticket.str.replace('SCA2037','SCA 2037')
df['Ticket'] = df.Ticket.str.replace('SCA2568','SCA 2568')
df[(df.Ticket.str[0:7]=='STON/O2')].Ticket.value_counts()

STON/O2 3101279    2
STON/O2 3101280    1
STON/O2 3101286    1
STON/O2 3101294    1
STON/O2 3101293    1
STON/O2 3101274    1
STON/O2 3101270    1
STON/O2 3101289    1
STON/O2 3101288    1
STON/O2 3101285    1
STON/O2 3101283    1
STON/O2 3101275    1
STON/O2 3101271    1
STON/O2 3101273    1
STON/O2 3101291    1
STON/O2 3101268    1
STON/O2 3101290    1
STON/O2 3101269    1
STON/O2 3101292    1
STON/O2 3101282    1
Name: Ticket, dtype: int64

In [30]:
df[(df.Ticket.str[0]=='S')].Ticket.value_counts()

SOC 14879           7
SC/PARIS 2123       4
SOTON/OQ 3101315    3
SC/PARIS 2079       3
SCA 3085            2
SCA 2037            2
SO/PP 3             2
STON/O2 3101279     2
SC/PARIS 2167       2
SO/PP 2             2
SW/PP 751           1
STON/OQ 369943      1
SC 14888            1
SOTON/OQ 3101263    1
STON/O2 3101289     1
SP 3464             1
SO/PP 752           1
SOTON/OQ 3101316    1
STON/O2 3101275     1
SCA3 2861           1
STON/O2 3101271     1
SOTON/O2 3101272    1
SOTON/OQ 3101262    1
STON/O2 3101293     1
SOTON/OQ 3101317    1
STON/O2 3101286     1
SC 1748             1
SCA 2568            1
SOTON/OQ 3101311    1
STON/O2 3101268     1
STON/O2 3101273     1
SOTON/OQ 392083     1
SOTON/OQ 3101307    1
SC/PARIS 2148       1
SOTON/OQ 392076     1
STON/O2 3101285     1
STON/O2 3101269     1
SCO/W 1585          1
STON/O2 3101274     1
SOTON/OQ 392089     1
SC/PARIS 2146       1
STON/O2 3101280     1
STON/O2 3101290     1
SOTON/OQ 392087     1
SOP 1166            1
SOTON/O2 3101284    1
SC/A4 23567         1
SOTON/OQ 3101306    1
STON/O2 3101291     1
STON/O2 3101270     1
SC/PARIS 2133       1
SC/PARIS 2149       1
SOTON/OQ 3101312    1
STON/O2 3101288     1
SO/PP 251           1
SOTON/OQ 3101314    1
SOTON/OQ 3101309    1
SO/PP 751           1
SC/PARIS 2159       1
SOTON/OQ 392078     1
SOTON/OQ 392082     1
STON/O2 3101292     1
SOTON/OQ 392090     1
SOTON/OQ 3101310    1
SC/PARIS 2163       1
SCA BASLE 541       1
SO/C 14885          1
STON/O2 3101282     1
STON/O2 3101294     1
SC/PARIS 2166       1
SC/PARIS 2147       1
SW/PP 752           1
SC/PARIS 2131       1
SC/PARIS 2168       1
STON/O2 3101283     1
SOTON/OQ 3101308    1
SOTON/OQ 392086     1
SOTON/O2 3101287    1
SOTON/OQ 3101305    1
Name: Ticket, dtype: int64

# Ticket Start with 'W'

In [31]:
df[(df.Ticket.str[0]=='W')].Ticket.value_counts()

W./C. 6608     5
W./C. 6607     4
WE/P 5735      2
W.E.P. 5734    2
W./C. 6609     1
W/C 14208      1
W./C. 14263    1
W./C. 14266    1
W./C. 14260    1
W./C. 14258    1
Name: Ticket, dtype: int64

In [32]:
df['Ticket'] = df.Ticket.str.replace('W./C.','W/C')
df['Ticket'] = df.Ticket.str.replace('WE/P','WEP')
df['Ticket'] = df.Ticket.str.replace('W.E.P.','WEP')

In [33]:
df[(df.Ticket.str[0]=='W')].Ticket.value_counts()

W/C 6608     5
W/C 6607     4
WEP 5734     2
WEP 5735     2
W/C 14258    1
W/C 14208    1
W/C 14260    1
W/C 14263    1
W/C 14266    1
W/C 6609     1
Name: Ticket, dtype: int64

# EMBARKED

In [34]:
df[(df.Embarked.isnull())]

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,source,Members,Last_name,First_name,Title
61,62,1.0,1,female,38.0,0,0,113572,80.0,B28,NaN,train,1,Icard,Amelie,Miss
829,830,1.0,1,female,62.0,0,0,113572,80.0,B28,NaN,train,1,Stone,George Nelson (Martha Evelyn),Mrs

In [35]:
df[(df.Ticket.str.len()==6)&(df.Pclass==1)&(df.Cabin.str[0]=='B')].sort_values('Ticket',ascending=False)

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,source,Members,Last_name,First_name,Title
802,803,1.0,1,male,11.0,1,2,113760,120.0000,B96 B98,S,train,4,Carter,William Thornton II,Master
763,764,1.0,1,female,36.0,1,2,113760,120.0000,B96 B98,S,train,4,Carter,William Ernest (Lucile Polk),Mrs
390,391,1.0,1,male,36.0,1,2,113760,120.0000,B96 B98,S,train,4,Carter,William Ernest,Mr
435,436,1.0,1,female,14.0,1,2,113760,120.0000,B96 B98,S,train,4,Carter,Lucile Polk,Miss
61,62,1.0,1,female,38.0,0,0,113572,80.0000,B28,NaN,train,1,Icard,Amelie,Miss
829,830,1.0,1,female,62.0,0,0,113572,80.0000,B28,NaN,train,1,Stone,George Nelson (Martha Evelyn),Mrs
54,55,0.0,1,male,65.0,0,1,113509,61.9792,B30,C,train,2,Ostby,Engelhart Cornelius,Mr
917,918,NaN,1,female,22.0,0,1,113509,61.9792,B36,C,test,2,Ostby,Helene Ragnhild,Miss
536,537,0.0,1,male,45.0,0,0,113050,26.5500,B38,S,train,1,Butt,Archibald Willingham,Major
1106,1107,NaN,1,male,42.0,0,0,113038,42.5000,B11,S,test,1,Head,Christopher,Mr
1196,1197,NaN,1,female,64.0,1,1,112901,26.5500,B26,S,test,3,Crosby,Edward Gifford (Catherine Elizabeth Halstead),Mrs
263,264,0.0,1,male,40.0,0,0,112059,0.0000,B94,S,train,1,Harrison,William,Mr
815,816,0.0,1,male,NaN,0,0,112058,0.0000,B102,S,train,1,Fry,Richard,Mr
1263,1264,NaN,1,male,49.0,0,0,112058,0.0000,B52 B54 B56,S,test,1,Ismay,Joseph Bruce,Mr
887,888,1.0,1,female,19.0,0,0,112053,30.0000,B42,S,train,1,Graham,Margaret Edith,Miss
523,524,1.0,1,female,44.0,0,1,111361,57.9792,B18,C,train,2,Hippach,Louis Albert (Ida Sophia Fischer),Mrs
329,330,1.0,1,female,16.0,0,1,111361,57.9792,B18,C,train,2,Hippach,Jean Gertrude,Miss
170,171,0.0,1,male,61.0,0,0,111240,33.5000,B19,S,train,1,Van der hoef,Wyckoff,Mr
504,505,1.0,1,female,16.0,0,0,110152,86.5000,B79,S,train,1,Maioni,Roberta,Miss
759,760,1.0,1,female,33.0,0,0,110152,86.5000,B77,S,train,1,Rothes,of (Lucy Noel Martha Dyer-Edwards),the Countess
257,258,1.0,1,female,30.0,0,0,110152,86.5000,B77,S,train,1,Cherry,Gladys,Miss

In [36]:
# Substitute the value 'S'

In [37]:
df.Embarked.fillna('S',inplace=True)

# DONE CLEANING ON TICKET COLUMN

In [38]:
df_fare = df.sort_values('Fare',ascending=False)

# NULL VALUES

In [39]:
df.isnull().sum()

PassengerId       0
Survived        418
Pclass            0
Sex               0
Age             263
SibSp             0
Parch             0
Ticket            0
Fare              1
Cabin          1014
Embarked          0
source            0
Members           0
Last_name         0
First_name        0
Title             0
dtype: int64

In [40]:
df.head(2)

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,source,Members,Last_name,First_name,Title
0,1,0.0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,train,2,Braund,Owen Harris,Mr
1,2,1.0,1,female,38.0,1,0,PC 17599,71.2833,C85,C,train,2,Cumings,John Bradley (Florence Briggs Thayer),Mrs

# Cabin

In [41]:
df['deck'] = df['Cabin'].copy()

In [42]:
df.head()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,source,Members,Last_name,First_name,Title,deck
0,1,0.0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,train,2,Braund,Owen Harris,Mr,NaN
1,2,1.0,1,female,38.0,1,0,PC 17599,71.2833,C85,C,train,2,Cumings,John Bradley (Florence Briggs Thayer),Mrs,C85
2,3,1.0,3,female,26.0,0,0,STON/O2 3101282,7.9250,NaN,S,train,1,Heikkinen,Laina,Miss,NaN
3,4,1.0,1,female,35.0,1,0,113803,53.1000,C123,S,train,2,Futrelle,Jacques Heath (Lily May Peel),Mrs,C123
4,5,0.0,3,male,35.0,0,0,373450,8.0500,NaN,S,train,1,Allen,William Henry,Mr,NaN

In [43]:
df[(df.Cabin.str[0]=='A')].PassengerId.count()

22

In [44]:
df[(df.Cabin.str[0]=='B')].PassengerId.count()

65

In [45]:
df[(df.Cabin.str[0]=='C')].PassengerId.count()

94

In [46]:
df[(df.Cabin.str[0]=='D')].PassengerId.count()

46

In [47]:
df[(df.Cabin.str[0]=='E')].PassengerId.count()

41

In [48]:
df[(df.Cabin.str[0]=='F')].PassengerId.count()

21

In [49]:
df[(df.Cabin.str[0]=='G')].PassengerId.count()

5

In [56]:
df[(df.Cabin.str[0]=='A')]

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,source,Members,Last_name,First_name,Title,deck,deck1,C1
23,24,1.0,1,male,28.0,0,0,113788,35.5000,A6,S,train,1,Sloper,William Thompson,Mr,A6,A6,None
96,97,0.0,1,male,71.0,0,0,PC 17754,34.6542,A5,C,train,1,Goldschmidt,George B,Mr,A5,A5,None
174,175,0.0,1,male,56.0,0,0,17764,30.6958,A7,C,train,1,Smith,James Clinch,Mr,A7,A7,None
185,186,0.0,1,male,NaN,0,0,113767,50.0000,A32,S,train,1,Rood,Hugh Roscoe,Mr,A32,A32,None
209,210,1.0,1,male,40.0,0,0,112277,31.0000,A31,C,train,1,Blank,Henry,Mr,A31,A31,None
284,285,0.0,1,male,NaN,0,0,113056,26.0000,A19,S,train,1,Smith,Richard William,Mr,A19,A19,None
445,446,1.0,1,male,4.0,0,2,33638,81.8583,A34,S,train,3,Dodge,Washington,Master,A34,A34,None
475,476,0.0,1,male,NaN,0,0,110465,52.0000,A14,S,train,1,Clifford,George Quincy,Mr,A14,A14,None
556,557,1.0,1,female,48.0,1,0,11755,39.6000,A16,C,train,2,Duff Gordon,"(Lucille Christiana Sutherland) (""Mrs Morgan"")",Lady,A16,A16,None
583,584,0.0,1,male,36.0,0,0,13049,40.1250,A10,C,train,1,Ross,John Hugo,Mr,A10,A10,None
599,600,1.0,1,male,49.0,1,0,PC 17485,56.9292,A20,C,train,2,Duff Gordon,"Cosmo Edmund (""Mr Morgan"")",Sir,A20,A20,None
630,631,1.0,1,male,80.0,0,0,27042,30.0000,A23,S,train,1,Barkworth,Algernon Henry Wilson,Mr,A23,A23,None
647,648,1.0,1,male,56.0,0,0,13213,35.5000,A26,C,train,1,Simonius-Blumer,Oberst Alfons,Col,A26,A26,None
806,807,0.0,1,male,39.0,0,0,112050,0.0000,A36,S,train,1,Andrews,Thomas Jr,Mr,A36,A36,None
867,868,0.0,1,male,31.0,0,0,PC 17590,50.4958,A24,S,train,1,Roebling,Washington Augustus II,Mr,A24,A24,None
919,920,NaN,1,male,41.0,0,0,113054,30.5000,A21,S,test,1,Brady,John Bertram,Mr,A21,A21,None
937,938,NaN,1,male,45.0,0,0,PC 17594,29.7000,A9,C,test,1,Chevre,Paul Romaine,Mr,A9,A9,None
1003,1004,NaN,1,female,36.0,0,0,PC 17531,31.6792,A29,C,test,1,Evans,Edith Corse,Miss,A29,A29,None
1099,1100,NaN,1,female,33.0,0,0,PC 17613,27.7208,A11,C,test,1,Rosenbaum,Edith Louise,Miss,A11,A11,None
1184,1185,NaN,1,male,53.0,1,1,33638,81.8583,A34,S,test,3,Dodge,Washington,Dr,A34,A34,None
1222,1223,NaN,1,male,39.0,0,0,PC 17580,29.7000,A18,C,test,1,Dulles,William Crothers,Mr,A18,A18,None
1265,1266,NaN,1,female,54.0,1,1,33638,81.8583,A34,S,test,3,Dodge,Washington (Ruth Vidaver),Mrs,A34,A34,None

In [57]:
df[(df.Cabin.str[0]=='B')]

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,source,Members,Last_name,First_name,Title,deck,deck1,C1
31,32,1.0,1,female,NaN,1,0,PC 17569,146.5208,B78,C,train,2,Spencer,William Augustus (Marie Eugenie),Mrs,B78,B78,None
54,55,0.0,1,male,65.0,0,1,113509,61.9792,B30,C,train,2,Ostby,Engelhart Cornelius,Mr,B30,B30,None
61,62,1.0,1,female,38.0,0,0,113572,80.0000,B28,S,train,1,Icard,Amelie,Miss,B28,B28,None
118,119,0.0,1,male,24.0,0,1,PC 17558,247.5208,B58 B60,C,train,2,Baxter,Quigg Edmond,Mr,B58 B60,B58 B60,None
139,140,0.0,1,male,24.0,0,0,PC 17593,79.2000,B86,C,train,1,Giglio,Victor,Mr,B86,B86,None
170,171,0.0,1,male,61.0,0,0,111240,33.5000,B19,S,train,1,Van der hoef,Wyckoff,Mr,B19,B19,None
194,195,1.0,1,female,44.0,0,0,PC 17610,27.7208,B4,C,train,1,Brown,James Joseph (Margaret Tobin),Mrs,B4,B4,None
195,196,1.0,1,female,58.0,0,0,PC 17569,146.5208,B80,C,train,1,Lurette,Elise,Miss,B80,B80,None
257,258,1.0,1,female,30.0,0,0,110152,86.5000,B77,S,train,1,Cherry,Gladys,Miss,B77,B77,None
263,264,0.0,1,male,40.0,0,0,112059,0.0000,B94,S,train,1,Harrison,William,Mr,B94,B94,None
291,292,1.0,1,female,19.0,1,0,11967,91.0792,B49,C,train,2,Bishop,Dickinson H (Helen Walton),Mrs,B49,B49,None
299,300,1.0,1,female,50.0,0,1,PC 17558,247.5208,B58 B60,C,train,2,Baxter,James (Helene DeLaudeniere Chaput),Mrs,B58 B60,B58 B60,None
311,312,1.0,1,female,18.0,2,2,PC 17608,262.3750,B57 B59 B63 B66,C,train,5,Ryerson,Emily Borie,Miss,B57 B59 B63 B66,B57 B59 B63 B66,None
329,330,1.0,1,female,16.0,0,1,111361,57.9792,B18,C,train,2,Hippach,Jean Gertrude,Miss,B18,B18,None
369,370,1.0,1,female,24.0,0,0,PC 17477,69.3000,B35,C,train,1,Aubart,Leontine Pauline,Mme,B35,B35,None
390,391,1.0,1,male,36.0,1,2,113760,120.0000,B96 B98,S,train,4,Carter,William Ernest,Mr,B96 B98,B96 B98,None
435,436,1.0,1,female,14.0,1,2,113760,120.0000,B96 B98,S,train,4,Carter,Lucile Polk,Miss,B96 B98,B96 B98,None
484,485,1.0,1,male,25.0,1,0,11967,91.0792,B49,C,train,2,Bishop,Dickinson H,Mr,B49,B49,None
487,488,0.0,1,male,58.0,0,0,11771,29.7000,B37,C,train,1,Kent,Edward Austin,Mr,B37,B37,None
504,505,1.0,1,female,16.0,0,0,110152,86.5000,B79,S,train,1,Maioni,Roberta,Miss,B79,B79,None
520,521,1.0,1,female,30.0,0,0,12749,93.5000,B73,S,train,1,Perreault,Anne,Miss,B73,B73,None
523,524,1.0,1,female,44.0,0,1,111361,57.9792,B18,C,train,2,Hippach,Louis Albert (Ida Sophia Fischer),Mrs,B18,B18,None
536,537,0.0,1,male,45.0,0,0,113050,26.5500,B38,S,train,1,Butt,Archibald Willingham,Major,B38,B38,None
539,540,1.0,1,female,22.0,0,2,13568,49.5000,B39,C,train,3,Frolicher,Hedwig Margaritha,Miss,B39,B39,None
540,541,1.0,1,female,36.0,0,2,WEP 5735,71.0000,B22,S,train,3,Crosby,Harriet R,Miss,B22,B22,None
587,588,1.0,1,male,60.0,1,1,13567,79.2000,B41,C,train,3,Frolicher-Stehli,Maxmillian,Mr,B41,B41,None
632,633,1.0,1,male,32.0,0,0,13214,30.5000,B50,C,train,1,Stahelin-Maeglin,Max,Dr,B50,B50,None
641,642,1.0,1,female,24.0,0,0,PC 17477,69.3000,B35,C,train,1,Sagesser,Emma,Mlle,B35,B35,None
671,672,0.0,1,male,31.0,1,0,FC 12750,52.0000,B71,S,train,2,Davidson,Thornton,Mr,B71,B71,None
679,680,1.0,1,male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C,train,2,Cardeza,Thomas Drake Martinez,Mr,B51 B53 B55,B51 B53 B55,None
689,690,1.0,1,female,15.0,0,1,24160,211.3375,B5,S,train,2,Madill,Georgette Alexandra,Miss,B5,B5,None
690,691,1.0,1,male,31.0,1,0,17474,57.0000,B20,S,train,2,Dick,Albert Adrian,Mr,B20,B20,None
730,731,1.0,1,female,29.0,0,0,24160,211.3375,B5,S,train,1,Allen,Elisabeth Walton,Miss,B5,B5,None
737,738,1.0,1,male,35.0,0,0,PC 17755,512.3292,B101,C,train,1,Lesurer,Gustave J,Mr,B101,B101,None
742,743,1.0,1,female,21.0,2,2,PC 17608,262.3750,B57 B59 B63 B66,C,train,5,Ryerson,"Susan Parker ""Suzette""",Miss,B57 B59 B63 B66,B57 B59 B63 B66,None
745,746,0.0,1,male,70.0,1,1,WEP 5735,71.0000,B22,S,train,3,Crosby,Edward Gifford,Capt,B22,B22,None
759,760,1.0,1,female,33.0,0,0,110152,86.5000,B77,S,train,1,Rothes,of (Lucy Noel Martha Dyer-Edwards),the Countess,B77,B77,None
763,764,1.0,1,female,36.0,1,2,113760,120.0000,B96 B98,S,train,4,Carter,William Ernest (Lucile Polk),Mrs,B96 B98,B96 B98,None
779,780,1.0,1,female,43.0,0,1,24160,211.3375,B3,S,train,2,Robert,Edward Scott (Elisabeth Walton McMillan),Mrs,B3,B3,None
781,782,1.0,1,female,17.0,1,0,17474,57.0000,B20,S,train,2,Dick,Albert Adrian (Vera Gillespie),Mrs,B20,B20,None
789,790,0.0,1,male,46.0,0,0,PC 17593,79.2000,B82 B84,C,train,1,Guggenheim,Benjamin,Mr,B82 B84,B82 B84,None
802,803,1.0,1,male,11.0,1,2,113760,120.0000,B96 B98,S,train,4,Carter,William Thornton II,Master,B96 B98,B96 B98,None
815,816,0.0,1,male,NaN,0,0,112058,0.0000,B102,S,train,1,Fry,Richard,Mr,B102,B102,None
820,821,1.0,1,female,52.0,1,1,12749,93.5000,B69,S,train,3,Hays,Charles Melville (Clara Jennings Gregg),Mrs,B69,B69,None
829,830,1.0,1,female,62.0,0,0,113572,80.0000,B28,S,train,1,Stone,George Nelson (Martha Evelyn),Mrs,B28,B28,None
872,873,0.0,1,male,33.0,0,0,695,5.0000,B51 B53 B55,S,train,1,Carlsson,Frans Olof,Mr,B51 B53 B55,B51 B53 B55,None
887,888,1.0,1,female,19.0,0,0,112053,30.0000,B42,S,train,1,Graham,Margaret Edith,Miss,B42,B42,None
903,904,NaN,1,female,23.0,1,0,21228,82.2667,B45,S,test,2,Snyder,John Pillsbury (Nelle Stevenson),Mrs,B45,B45,None
915,916,NaN,1,female,48.0,1,3,PC 17608,262.3750,B57 B59 B63 B66,C,test,5,Ryerson,Arthur Larned (Emily Maria Borie),Mrs,B57 B59 B63 B66,B57 B59 B63 B66,None
917,918,NaN,1,female,22.0,0,1,113509,61.9792,B36,C,test,2,Ostby,Helene Ragnhild,Miss,B36,B36,None
950,951,NaN,1,female,36.0,0,0,PC 17608,262.3750,B61,C,test,1,Chaudanson,Victorine,Miss,B61,B61,None
955,956,NaN,1,male,13.0,2,2,PC 17608,262.3750,B57 B59 B63 B66,C,test,5,Ryerson,John Borie,Master,B57 B59 B63 B66,B57 B59 B63 B66,None
983,984,NaN,1,female,27.0,1,2,FC 12750,52.0000,B71,S,test,4,Davidson,Thornton (Orian Hays),Mrs,B71,B71,None
1033,1034,NaN,1,male,61.0,1,3,PC 17608,262.3750,B57 B59 B63 B66,C,test,5,Ryerson,Arthur Larned,Mr,B57 B59 B63 B66,B57 B59 B63 B66,None
1057,1058,NaN,1,male,48.0,0,0,PC 17591,50.4958,B10,C,test,1,Brandeis,Emil,Mr,B10,B10,None
1075,1076,NaN,1,female,27.0,1,1,PC 17558,247.5208,B58 B60,C,test,3,Douglas,Frederick Charles (Mary Helene Baxter),Mrs,B58 B60,B58 B60,None
1106,1107,NaN,1,male,42.0,0,0,113038,42.5000,B11,S,test,1,Head,Christopher,Mr,B11,B11,None
1178,1179,NaN,1,male,24.0,1,0,21228,82.2667,B45,S,test,2,Snyder,John Pillsbury,Mr,B45,B45,None
1196,1197,NaN,1,female,64.0,1,1,112901,26.5500,B26,S,test,3,Crosby,Edward Gifford (Catherine Elizabeth Halstead),Mrs,B26,B26,None
1199,1200,NaN,1,male,55.0,1,1,12749,93.5000,B69,S,test,3,Hays,Charles Melville,Mr,B69,B69,None
1207,1208,NaN,1,male,57.0,1,0,PC 17569,146.5208,B78,C,test,2,Spencer,William Augustus,Mr,B78,B78,None
1234,1235,NaN,1,female,58.0,0,1,PC 17755,512.3292,B51 B53 B55,C,test,2,Cardeza,James Warburton Martinez (Charlotte Wardle Dr...,Mrs,B51 B53 B55,B51 B53 B55,None
1263,1264,NaN,1,male,49.0,0,0,112058,0.0000,B52 B54 B56,S,test,1,Ismay,Joseph Bruce,Mr,B52 B54 B56,B52 B54 B56,None
1281,1282,NaN,1,male,23.0,0,0,12749,93.5000,B24,S,test,1,Payne,Vivian Ponsonby,Mr,B24,B24,None
1288,1289,NaN,1,female,48.0,1,1,13567,79.2000,B41,C,test,3,Frolicher-Stehli,Maxmillian (Margaretha Emerentia Stehli),Mrs,B41,B41,None

In [58]:
df[(df.Cabin.str[0]=='C')]

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,source,Members,Last_name,First_name,Title,deck,deck1,C1
1,2,1.0,1,female,38.00,1,0,PC 17599,71.2833,C85,C,train,2,Cumings,John Bradley (Florence Briggs Thayer),Mrs,C85,C85,None
3,4,1.0,1,female,35.00,1,0,113803,53.1000,C123,S,train,2,Futrelle,Jacques Heath (Lily May Peel),Mrs,C123,C123,None
11,12,1.0,1,female,58.00,0,0,113783,26.5500,C103,S,train,1,Bonnell,Elizabeth,Miss,C103,C103,None
27,28,0.0,1,male,19.00,3,2,19950,263.0000,C23 C25 C27,S,train,6,Fortune,Charles Alexander,Mr,C23 C25 C27,C23 C25 C27,None
55,56,1.0,1,male,NaN,0,0,19947,35.5000,C52,S,train,1,Woolner,Hugh,Mr,C52,C52,None
62,63,0.0,1,male,45.00,1,0,36973,83.4750,C83,S,train,2,Harris,Henry Birkhardt,Mr,C83,C83,None
88,89,1.0,1,female,23.00,3,2,19950,263.0000,C23 C25 C27,S,train,6,Fortune,Mabel Helen,Miss,C23 C25 C27,C23 C25 C27,None
110,111,0.0,1,male,47.00,0,0,110465,52.0000,C110,S,train,1,Porter,Walter Chamberlain,Mr,C110,C110,None
137,138,0.0,1,male,37.00,1,0,113803,53.1000,C123,S,train,2,Futrelle,Jacques Heath,Mr,C123,C123,None
151,152,1.0,1,female,22.00,1,0,113776,66.6000,C2,S,train,2,Pears,Thomas (Edith Wearne),Mrs,C2,C2,None
177,178,0.0,1,female,50.00,0,0,PC 17595,28.7125,C49,C,train,1,Isham,Ann Elizabeth,Miss,C49,C49,None
224,225,1.0,1,male,38.00,1,0,19943,90.0000,C93,S,train,2,Hoyt,Frederick Maxfield,Mr,C93,C93,None
230,231,1.0,1,female,35.00,1,0,36973,83.4750,C83,S,train,2,Harris,Henry Birkhardt (Irene Wallach),Mrs,C83,C83,None
245,246,0.0,1,male,44.00,2,0,19928,90.0000,C78,Q,train,3,Minahan,William Edward,Dr,C78,C78,None
252,253,0.0,1,male,62.00,0,0,113514,26.5500,C87,S,train,1,Stead,William Thomas,Mr,C87,C87,None
268,269,1.0,1,female,58.00,0,1,PC 17582,153.4625,C125,S,train,2,Graham,William Thompson (Edith Junkins),Mrs,C125,C125,None
269,270,1.0,1,female,35.00,0,0,PC 17760,135.6333,C99,S,train,1,Bissette,Amelia,Miss,C99,C99,None
273,274,0.0,1,male,37.00,0,1,PC 17596,29.7000,C118,C,train,2,Natsch,Charles H,Mr,C118,C118,None
297,298,0.0,1,female,2.00,1,2,113781,151.5500,C22 C26,S,train,4,Allison,Helen Loraine,Miss,C22 C26,C22 C26,None
298,299,1.0,1,male,NaN,0,0,19988,30.5000,C106,S,train,1,Saalfeld,Adolphe,Mr,C106,C106,None
305,306,1.0,1,male,0.92,1,2,113781,151.5500,C22 C26,S,train,4,Allison,Hudson Trevor,Master,C22 C26,C22 C26,None
307,308,1.0,1,female,17.00,1,0,PC 17758,108.9000,C65,C,train,2,Penasco y Castellana,Victor de Satode (Maria Josefa Perez de Soto ...,Mrs,C65,C65,None
310,311,1.0,1,female,24.00,0,0,11767,83.1583,C54,C,train,1,Hays,Margaret Bechstein,Miss,C54,C54,None
318,319,1.0,1,female,31.00,0,2,36928,164.8667,C7,S,train,3,Wick,Mary Natalie,Miss,C7,C7,None
325,326,1.0,1,female,36.00,0,0,PC 17760,135.6333,C32,C,train,1,Young,Marie Grice,Miss,C32,C32,None
331,332,0.0,1,male,45.50,0,0,113043,28.5000,C124,S,train,1,Partner,Austen,Mr,C124,C124,None
332,333,0.0,1,male,38.00,0,1,PC 17582,153.4625,C91,S,train,2,Graham,George Edward,Mr,C91,C91,None
336,337,0.0,1,male,29.00,1,0,113776,66.6000,C2,S,train,2,Pears,Thomas Clinton,Mr,C2,C2,None
341,342,1.0,1,female,24.00,3,2,19950,263.0000,C23 C25 C27,S,train,6,Fortune,Alice Elizabeth,Miss,C23 C25 C27,C23 C25 C27,None
351,352,0.0,1,male,NaN,0,0,113510,35.0000,C128,S,train,1,Williams-Lambert,Fletcher Fellows,Mr,C128,C128,None
377,378,0.0,1,male,27.00,0,2,113503,211.5000,C82,C,train,3,Widener,Harry Elkins,Mr,C82,C82,None
412,413,1.0,1,female,33.00,1,0,19928,90.0000,C78,Q,train,2,Minahan,Daisy E,Miss,C78,C78,None
430,431,1.0,1,male,28.00,0,0,110564,26.5500,C52,S,train,1,Bjornstrom-Steffansson,Mauritz Hakan,Mr,C52,C52,None
438,439,0.0,1,male,64.00,1,4,19950,263.0000,C23 C25 C27,S,train,6,Fortune,Mark,Mr,C23 C25 C27,C23 C25 C27,None
449,450,1.0,1,male,52.00,0,0,113786,30.5000,C104,S,train,1,Peuchen,Arthur Godfrey,Major,C104,C104,None
452,453,0.0,1,male,30.00,0,0,113051,27.7500,C111,C,train,1,Foreman,Benjamin Laventall,Mr,C111,C111,None
453,454,1.0,1,male,49.00,1,0,17453,89.1042,C92,C,train,2,Goldenberg,Samuel L,Mr,C92,C92,None
486,487,1.0,1,female,35.00,1,0,19943,90.0000,C93,S,train,2,Hoyt,Frederick Maxfield (Jane Anne Forby),Mrs,C93,C93,None
492,493,0.0,1,male,55.00,0,0,113787,30.5000,C30,S,train,1,Molson,Harry Markland,Mr,C30,C30,None
498,499,0.0,1,female,25.00,1,2,113781,151.5500,C22 C26,S,train,4,Allison,Hudson J C (Bessie Waldo Daniels),Mrs,C22 C26,C22 C26,None
505,506,0.0,1,male,18.00,1,0,PC 17758,108.9000,C65,C,train,2,Penasco y Castellana,Victor de Satode,Mr,C65,C65,None
527,528,0.0,1,male,NaN,0,0,PC 17483,221.7792,C95,S,train,1,Farthing,John,Mr,C95,C95,None
544,545,0.0,1,male,50.00,1,0,PC 17761,106.4250,C86,C,train,2,Douglas,Walter Donald,Mr,C86,C86,None
550,551,1.0,1,male,17.00,0,2,17421,110.8833,C70,C,train,3,Thayer,John Borland Jr,Mr,C70,C70,None
571,572,1.0,1,female,53.00,2,0,11769,51.4792,C101,S,train,3,Appleton,Edward Dale (Charlotte Lamson),Mrs,C101,C101,None
581,582,1.0,1,female,39.00,1,1,17421,110.8833,C68,C,train,3,Thayer,John Borland (Marian Longstreth Morris),Mrs,C68,C68,None
609,610,1.0,1,female,40.00,0,0,PC 17582,153.4625,C125,S,train,1,Shutes,Elizabeth W,Miss,C125,C125,None
669,670,1.0,1,female,NaN,1,0,19996,52.0000,C126,S,train,2,Taylor,Elmer Zebley (Juliet Cummins Wright),Mrs,C126,C126,None
698,699,0.0,1,male,49.00,1,1,17421,110.8833,C68,C,train,3,Thayer,John Borland,Mr,C68,C68,None
700,701,1.0,1,female,18.00,1,0,PC 17757,227.5250,C62 C64,C,train,2,Astor,John Jacob (Madeleine Talmadge Force),Mrs,C62 C64,C62 C64,None
710,711,1.0,1,female,24.00,0,0,PC 17482,49.5042,C90,C,train,1,Mayne,"Berthe Antonine (""Mrs de Villiers"")",Mlle,C90,C90,None
711,712,0.0,1,male,NaN,0,0,113028,26.5500,C124,S,train,1,Klaber,Herman,Mr,C124,C124,None
712,713,1.0,1,male,48.00,1,0,19996,52.0000,C126,S,train,2,Taylor,Elmer Zebley,Mr,C126,C126,None
716,717,1.0,1,female,38.00,0,0,PC 17757,227.5250,C45,C,train,1,Endres,Caroline Louise,Miss,C45,C45,None
741,742,0.0,1,male,36.00,1,0,19877,78.8500,C46,S,train,2,Cavendish,Tyrell William,Mr,C46,C46,None
839,840,1.0,1,male,NaN,0,0,11774,29.7000,C47,C,train,1,Marechal,Pierre,Mr,C47,C47,None
849,850,1.0,1,female,NaN,1,0,17453,89.1042,C92,C,train,2,Goldenberg,Samuel L (Edwiga Grabowska),Mrs,C92,C92,None
879,880,1.0,1,female,56.00,0,1,11767,83.1583,C50,C,train,2,Potter,Thomas Jr (Lily Alexenia Wilson),Mrs,C50,C50,None
889,890,1.0,1,male,26.00,0,0,111369,30.0000,C148,C,train,1,Behr,Karl Howell,Mr,C148,C148,None
925,926,NaN,1,male,30.00,1,0,13236,57.7500,C78,C,test,2,Mock,Philipp Edmund,Mr,C78,C78,None
941,942,NaN,1,male,24.00,1,0,13695,60.0000,C31,S,test,2,Smith,Lucien Philip,Mr,C31,C31,None
944,945,NaN,1,female,28.00,3,2,19950,263.0000,C23 C25 C27,S,test,6,Fortune,Ethel Flora,Miss,C23 C25 C27,C23 C25 C27,None
959,960,NaN,1,male,31.00,0,0,2543,28.5375,C53,C,test,1,Tucker,Gilbert Milligan Jr,Mr,C53,C53,None
960,961,NaN,1,female,60.00,1,4,19950,263.0000,C23 C25 C27,S,test,6,Fortune,Mark (Mary McDougald),Mrs,C23 C25 C27,C23 C25 C27,None
965,966,NaN,1,female,35.00,0,0,113503,211.5000,C130,C,test,1,Geiger,Amalie,Miss,C130,C130,None
966,967,NaN,1,male,32.50,0,0,113503,211.5000,C132,C,test,1,Keeping,Edwin,Mr,C132,C132,None
968,969,NaN,1,female,55.00,2,0,11770,25.7000,C101,S,test,3,Cornell,Robert Clifford (Malvina Helen Lamson),Mrs,C101,C101,None
972,973,NaN,1,male,67.00,1,0,PC 17483,221.7792,C55 C57,S,test,2,Straus,Isidor,Mr,C55 C57,C55 C57,None
987,988,NaN,1,female,76.00,1,0,19877,78.8500,C46,S,test,2,Cavendish,Tyrell William (Julia Florence Siegel),Mrs,C46,C46,None
991,992,NaN,1,female,43.00,1,0,11778,55.4417,C116,C,test,2,Stengel,Charles Emil Henry (Annie May Morris),Mrs,C116,C116,None
1005,1006,NaN,1,female,63.00,1,0,PC 17483,221.7792,C55 C57,S,test,2,Straus,Isidor (Rosalie Ida Blun),Mrs,C55 C57,C55 C57,None
1009,1010,NaN,1,male,36.00,0,0,13050,75.2417,C6,C,test,1,Beattie,Thomson,Mr,C6,C6,None
1013,1014,NaN,1,female,35.00,1,0,13236,57.7500,C28,C,test,2,Schabert,Paul (Emma Mock),Mrs,C28,C28,None
1022,1023,NaN,1,male,53.00,0,0,113780,28.5000,C51,C,test,1,Gracie,Archibald IV,Col,C51,C51,None
1041,1042,NaN,1,female,23.00,0,1,11767,83.1583,C54,C,test,2,Earnshaw,Boulton (Olive Potter),Mrs,C54,C54,None
1047,1048,NaN,1,female,29.00,0,0,PC 17483,221.7792,C97,S,test,1,Bird,Ellen,Miss,C97,C97,None
1068,1069,NaN,1,male,54.00,1,0,11778,55.4417,C116,C,test,2,Stengel,Charles Emil Henry,Mr,C116,C116,None
1093,1094,NaN,1,male,47.00,1,0,PC 17757,227.5250,C62 C64,C,test,2,Astor,John Jacob,Col,C62 C64,C62 C64,None
1109,1110,NaN,1,female,50.00,1,1,113503,211.5000,C80,C,test,3,Widener,George Dunton (Eleanor Elkins),Mrs,C80,C80,None
1125,1126,NaN,1,male,39.00,1,0,PC 17599,71.2833,C85,C,test,2,Cumings,John Bradley,Mr,C85,C85,None
1130,1131,NaN,1,female,48.00,1,0,PC 17761,106.4250,C86,C,test,2,Douglas,Walter Donald (Mahala Dutton),Mrs,C86,C86,None
1143,1144,NaN,1,male,27.00,1,0,13508,136.7792,C89,C,test,2,Clark,Walter Miller,Mr,C89,C89,None
1161,1162,NaN,1,male,46.00,0,0,13050,75.2417,C6,C,test,1,McCaffry,Thomas Francis,Mr,C6,C6,None
1163,1164,NaN,1,female,26.00,1,0,13508,136.7792,C89,C,test,2,Clark,Walter Miller (Virginia McDowell),Mrs,C89,C89,None
1197,1198,NaN,1,male,30.00,1,2,113781,151.5500,C22 C26,S,test,4,Allison,Hudson Joshua Creighton,Mr,C22 C26,C22 C26,None
1205,1206,NaN,1,female,55.00,0,0,PC 17760,135.6333,C32,C,test,1,White,John Stuart (Ella Holmes),Mrs,C32,C32,None
1226,1227,NaN,1,male,30.00,0,0,110469,26.0000,C106,S,test,1,Maguire,John Edward,Mr,C106,C106,None
1247,1248,NaN,1,female,59.00,2,0,11769,51.4792,C101,S,test,3,Brown,John Murray (Caroline Lane Lamson),Mrs,C101,C101,None
1269,1270,NaN,1,male,55.00,0,0,680,50.0000,C39,S,test,1,Hipkins,William Edward,Mr,C39,C39,None
1286,1287,NaN,1,female,18.00,1,0,13695,60.0000,C31,S,test,2,Smith,Lucien Philip (Mary Eloise Hughes),Mrs,C31,C31,None
1291,1292,NaN,1,female,30.00,0,0,36928,164.8667,C7,S,test,1,Bonnell,Caroline,Miss,C7,C7,None
1298,1299,NaN,1,male,50.00,1,1,113503,211.5000,C80,C,test,3,Widener,George Dunton,Mr,C80,C80,None
1302,1303,NaN,1,female,37.00,1,0,19928,90.0000,C78,Q,test,2,Minahan,William Edward (Lillian E Thorpe),Mrs,C78,C78,None
1305,1306,NaN,1,female,39.00,0,0,PC 17758,108.9000,C105,C,test,1,Oliva y Ocana,Fermina,Dona,C105,C105,None

In [62]:
df[(df.Cabin.str[0]=='D')].sort_values('Pclass',ascending=True)

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,source,Members,Last_name,First_name,Title,deck,deck1,C1
645,646,1.0,1,male,48.0,1,0,PC 17572,76.7292,D33,C,train,2,Harper,Henry Sleeper,Mr,D33,D33,None
1295,1296,NaN,1,male,43.0,1,0,17765,27.7208,D40,C,test,2,Frauenthal,Isaac Gerald,Mr,D40,D40,None
659,660,0.0,1,male,58.0,0,2,35273,113.2750,D48,C,train,3,Newell,Arthur Webster,Mr,D48,D48,None
681,682,1.0,1,male,27.0,0,0,PC 17572,76.7292,D49,C,train,1,Hassab,Hammad,Mr,D49,D49,None
740,741,1.0,1,male,NaN,0,0,16988,30.0000,D45,S,train,1,Hawksford,Walter James,Mr,D45,D45,None
748,749,0.0,1,male,19.0,1,0,113773,53.1000,D30,S,train,2,Marvin,Daniel Warner,Mr,D30,D30,None
765,766,1.0,1,female,51.0,1,0,13502,77.9583,D11,S,train,2,Hogeboom,John C (Anna Andrews),Mrs,D11,D11,None
782,783,0.0,1,male,29.0,0,0,113501,30.0000,D6,S,train,1,Long,Milton Clyde,Mr,D6,D6,None
796,797,1.0,1,female,49.0,0,0,17465,25.9292,D17,S,train,1,Leader,Alice (Farnham),Dr,D17,D17,None
853,854,1.0,1,female,16.0,0,1,PC 17592,39.4000,D28,S,train,2,Lines,Mary Conover,Miss,D28,D28,None
862,863,1.0,1,female,48.0,0,0,17466,25.9292,D17,S,train,1,Swift,Frederick Joel (Margaret Welles Barron),Mrs,D17,D17,None
871,872,1.0,1,female,47.0,1,1,11751,52.5542,D35,S,train,3,Beckwith,Richard Leonard (Sallie Monypeny),Mrs,D35,D35,None
932,933,NaN,1,male,NaN,0,0,113778,26.5500,D34,S,test,1,Franklin,Thomas Parham,Mr,D34,D34,None
935,936,NaN,1,female,45.0,1,0,11753,52.5542,D19,S,test,2,Kimball,Edwin Nelson Jr (Gertrude Parsons),Mrs,D19,D19,None
939,940,NaN,1,female,60.0,0,0,11813,76.2917,D15,C,test,1,Bucknell,William Robert (Emma Eliza Ward),Mrs,D15,D15,None
964,965,NaN,1,male,28.5,0,0,PC 17562,27.7208,D43,C,test,1,Ovies y Rodriguez,Servando,Mr,D43,D43,None
1049,1050,NaN,1,male,42.0,0,0,110489,26.5500,D22,S,test,1,Borebank,John James,Mr,D22,D22,None
1073,1074,NaN,1,female,18.0,1,0,113773,53.1000,D30,S,test,2,Marvin,Daniel Warner (Mary Graham Carmichael Farquar...,Mrs,D30,D30,None
627,628,1.0,1,female,21.0,0,0,13502,77.9583,D9,S,train,1,Longley,Gretchen Fiske,Miss,D9,D9,None
1127,1128,NaN,1,male,64.0,1,0,110813,75.2500,D37,C,test,2,Warren,Frank Manley,Mr,D37,D37,None
625,626,0.0,1,male,61.0,0,0,36963,32.3208,D50,S,train,1,Sutton,Frederick,Mr,D50,D50,None
591,592,1.0,1,female,52.0,1,0,36947,78.2667,D20,C,train,2,Stephenson,Walter Bertram (Martha Eustis),Mrs,D20,D20,None
52,53,1.0,1,female,49.0,1,0,PC 17572,76.7292,D33,C,train,2,Harper,Henry Sleeper (Myna Haxtun),Mrs,D33,D33,None
97,98,1.0,1,male,23.0,0,1,PC 17759,63.3583,D10 D12,C,train,2,Greenfield,William Bertram,Mr,D10 D12,D10 D12,None
102,103,0.0,1,male,21.0,0,1,35281,77.2875,D26,S,train,2,White,Richard Frasar,Mr,D26,D26,None
124,125,0.0,1,male,54.0,0,1,35281,77.2875,D26,S,train,2,White,Percival Wayland,Mr,D26,D26,None
136,137,1.0,1,female,19.0,0,2,11752,26.2833,D47,S,train,3,Newsom,Helen Monypeny,Miss,D47,D47,None
215,216,1.0,1,female,31.0,1,0,35273,113.2750,D36,C,train,2,Newell,Madeleine,Miss,D36,D36,None
218,219,1.0,1,female,32.0,0,0,11813,76.2917,D15,C,train,1,Bazzani,Albina,Miss,D15,D15,None
248,249,1.0,1,male,37.0,1,1,11751,52.5542,D35,S,train,3,Beckwith,Richard Leonard,Mr,D35,D35,None
275,276,1.0,1,female,63.0,1,0,13502,77.9583,D7,S,train,2,Andrews,Kornelia Theodosia,Miss,D7,D7,None
1282,1283,NaN,1,female,51.0,0,1,PC 17592,39.4000,D28,S,test,2,Lines,Ernest H (Elizabeth Lindsey James),Mrs,D28,D28,None
1241,1242,NaN,1,female,45.0,0,1,PC 17759,63.3583,D10 D12,C,test,2,Greenfield,Leo David (Blanche Strouse),Mrs,D10 D12,D10 D12,None
366,367,1.0,1,female,60.0,1,0,110813,75.2500,D37,C,train,2,Warren,Frank Manley (Anna Sophia Atkinson),Mrs,D37,D37,None
393,394,1.0,1,female,23.0,1,0,35273,113.2750,D36,C,train,2,Newell,Marjorie,Miss,D36,D36,None
457,458,1.0,1,female,NaN,1,0,17464,51.8625,D21,S,train,2,Kenyon,Frederick R (Marion),Mrs,D21,D21,None
496,497,1.0,1,female,54.0,1,0,36947,78.2667,D20,C,train,2,Eustis,Elizabeth Mussey,Miss,D20,D20,None
515,516,0.0,1,male,47.0,0,0,36967,34.0208,D46,S,train,1,Walker,William Anderson,Mr,D46,D46,None
621,622,1.0,1,male,42.0,1,0,11753,52.5542,D19,S,train,2,Kimball,Edwin Nelson Jr,Mr,D19,D19,None
1136,1137,NaN,1,male,41.0,1,0,17464,51.8625,D21,S,test,2,Kenyon,Frederick R,Mr,D21,D21,None
1192,1193,NaN,2,male,NaN,0,0,237735,15.0458,D,C,test,1,Malachard,Noel,Mr,D,D,None
21,22,1.0,2,male,34.0,0,0,248698,13.0000,D56,S,train,1,Beesley,Lawrence,Mr,D56,D56,None
327,328,1.0,2,female,36.0,0,0,28551,13.0000,D,S,train,1,Ball,(Ada E Hall),Mrs,D,D,None
292,293,0.0,2,male,36.0,0,0,SC/PARIS 2163,12.8750,D,C,train,1,Levy,Rene Jacques,Mr,D,D,None
473,474,1.0,2,female,23.0,0,0,SCA BASLE 541,13.7917,D,C,train,1,Jerwan,Amin S (Marie Marthe Thuillard),Mrs,D,D,None
1296,1297,NaN,2,male,20.0,0,0,SC/PARIS 2166,13.8625,D38,C,test,1,Nourney,"Alfred (Baron von Drachstedt"")""",Mr,D38,D38,None

In [60]:
df[(df.Cabin.str[0]=='E')].sort_values('Pclass',ascending=True)

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,source,Members,Last_name,First_name,Title,deck,deck1,C1
6,7,0.0,1,male,54.0,0,0,17463,51.8625,E46,S,train,1,McCarthy,Timothy J,Mr,E46,E46,None
1255,1256,NaN,1,female,25.0,1,0,11765,55.4417,E50,C,test,2,Harder,George Achilles (Dorothy Annan),Mrs,E50,E50,None
662,663,0.0,1,male,47.0,0,0,5727,25.5875,E58,S,train,1,Colley,Edward Pomeroy,Mr,E58,E58,None
701,702,1.0,1,male,35.0,0,0,PC 17475,26.2875,E24,S,train,1,Silverthorne,Spencer Victor,Mr,E24,E24,None
707,708,1.0,1,male,42.0,0,0,PC 17476,26.2875,E24,S,train,1,Calderhead,Edward Pennington,Mr,E24,E24,None
724,725,1.0,1,male,27.0,1,0,113806,53.1000,E8,S,train,2,Chambers,Norman Campbell,Mr,E8,E8,None
809,810,1.0,1,female,33.0,1,0,113806,53.1000,E8,S,train,2,Chambers,Norman Campbell (Bertha Griggs),Mrs,E8,E8,None
835,836,1.0,1,female,39.0,1,1,PC 17756,83.1583,E49,C,train,3,Compton,Sara Rebecca,Miss,E49,E49,None
857,858,1.0,1,male,51.0,0,0,113055,26.5500,E17,S,train,1,Daly,Peter Denis,Mr,E17,E17,None
905,906,NaN,1,female,47.0,1,0,WEP 5734,61.1750,E31,S,test,2,Chaffee,Herbert Fuller (Carrie Constance Toogood),Mrs,E31,E31,None
1037,1038,NaN,1,male,NaN,0,0,17463,51.8625,E46,S,test,1,Hilliard,Herbert Henry,Mr,E46,E46,None
1070,1071,NaN,1,female,64.0,0,2,PC 17756,83.1583,E45,C,test,3,Compton,Alexander Taylor (Mary Eliza Ingersoll),Mrs,E45,E45,None
1072,1073,NaN,1,male,37.0,1,1,PC 17756,83.1583,E52,C,test,3,Compton,Alexander Taylor Jr,Mr,E52,E52,None
1087,1088,NaN,1,male,6.0,0,2,16966,134.5000,E34,C,test,3,Spedden,Robert Douglas,Master,E34,E34,None
1133,1134,NaN,1,male,45.0,1,1,16966,134.5000,E34,C,test,3,Spedden,Frederic Oakley,Mr,E34,E34,None
1246,1247,NaN,1,male,50.0,0,0,113044,26.0000,E60,S,test,1,Julian,Henry Forbes,Mr,E60,E60,None
577,578,1.0,1,female,39.0,1,0,13507,55.9000,E44,S,train,2,Silvey,William Baird (Alice Munger),Mrs,E44,E44,None
572,573,1.0,1,male,36.0,0,0,PC 17474,26.3875,E25,S,train,1,Flynn,"John Irwin (""Irving"")",Mr,E25,E25,None
585,586,1.0,1,female,18.0,0,2,110413,79.6500,E68,S,train,3,Taussig,Ruth,Miss,E68,E68,None
512,513,1.0,1,male,36.0,0,0,PC 17473,26.2875,E25,S,train,1,McGough,James Robert,Mr,E25,E25,None
92,93,0.0,1,male,46.0,1,0,WEP 5734,61.1750,E31,S,train,2,Chaffee,Herbert Fuller,Mr,E31,E31,None
166,167,1.0,1,female,NaN,0,1,113505,55.0000,E33,S,train,2,Chibnall,(Edith Martha Bowerman),Mrs,E33,E33,None
262,263,0.0,1,male,52.0,1,1,110413,79.6500,E67,S,train,3,Taussig,Emil,Mr,E67,E67,None
309,310,1.0,1,female,30.0,0,0,PC 17485,56.9292,E36,C,train,1,Francatelli,Laura Mabel,Miss,E36,E36,None
319,320,1.0,1,female,40.0,1,1,16966,134.5000,E34,C,train,3,Spedden,Frederic Oakley (Margaretta Corning Stone),Mrs,E34,E34,None
337,338,1.0,1,female,41.0,0,0,16966,134.5000,E40,C,train,1,Burns,Elizabeth Margaret,Miss,E40,E40,None
356,357,1.0,1,female,22.0,0,1,113505,55.0000,E33,S,train,2,Bowerman,Elsie Edith,Miss,E33,E33,None
558,559,1.0,1,female,39.0,1,1,110413,79.6500,E67,S,train,3,Taussig,Emil (Tillie Mandelbaum),Mrs,E67,E67,None
1262,1263,NaN,1,female,31.0,0,0,16966,134.5000,E39 E41,C,test,1,Wilson,Helen Alice,Miss,E39 E41,E39 E41,None
434,435,0.0,1,male,50.0,1,0,13507,55.9000,E44,S,train,2,Silvey,William Baird,Mr,E44,E44,None
456,457,0.0,1,male,65.0,0,0,13509,26.5500,E38,S,train,1,Millet,Francis Davis,Mr,E38,E38,None
460,461,1.0,1,male,48.0,0,0,19952,26.5500,E12,S,train,1,Anderson,Harry,Mr,E12,E12,None
462,463,0.0,1,male,47.0,0,0,111320,38.5000,E63,S,train,1,Gee,Arthur H,Mr,E63,E63,None
370,371,1.0,1,male,25.0,1,0,11765,55.4417,E50,C,train,2,Harder,George Achilles,Mr,E50,E50,None
772,773,0.0,2,female,57.0,0,0,SO/PP 3,10.5000,E77,S,train,1,Mack,(Mary),Mrs,E77,E77,None
717,718,1.0,2,female,27.0,0,0,34218,10.5000,E101,S,train,1,Troutt,"Edwina Celia ""Winnie""",Miss,E101,E101,None
303,304,1.0,2,female,NaN,0,0,226593,12.3500,E101,Q,train,1,Keane,Nora A,Miss,E101,E101,None
123,124,1.0,2,female,32.5,0,0,27267,13.0000,E101,S,train,1,Webber,Susan,Miss,E101,E101,None
751,752,1.0,3,male,6.0,0,1,392096,12.4750,E121,S,train,2,Moor,Meier,Master,E121,E121,None
429,430,1.0,3,male,32.0,0,0,SOTON/OQ 392078,8.0500,E10,S,train,1,Pickard,Berk (Berk Trembisky),Mr,E10,E10,None
823,824,1.0,3,female,27.0,0,1,392096,12.4750,E121,S,train,2,Moor,(Beila),Mrs,E121,E121,None

In [61]:
df[(df.Cabin.str[0]=='E')]['Cabin'].str.split(pat="E", n=1, expand=True)

     0       1
6           46
92          31
123        101
166         33
262         67
303        101
309         36
319         34
337         40
356         33
370         50
429         10
434         44
456         38
460         12
462         63
512         25
558         67
572         25
577         44
585         68
662         58
701         24
707         24
717        101
724          8
751        121
772         77
809          8
823        121
835         49
857         17
905         31
1037        46
1070        45
1072        52
1087        34
1133        34
1246        60
1255        50
1262    39 E41

In [63]:
df[(df.Cabin.str[0]=='F')].sort_values('Pclass',ascending=True)

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,source,Members,Last_name,First_name,Title,deck,deck1,C1
66,67,1.0,2,female,29.0,0,0,CA 2395,10.5000,F33,S,train,1,Nye,(Elizabeth Ramell),Mrs,F33,F33,None
1113,1114,NaN,2,female,22.0,0,0,W/C 14266,10.5000,F33,S,test,1,Cook,(Selena Rogers),Mrs,F33,F33,None
1069,1070,NaN,2,female,36.0,0,3,230136,39.0000,F4,S,test,4,Becker,Allen Oliver (Nellie E Baumgardner),Mrs,F4,F4,None
1000,1001,NaN,2,male,18.5,0,0,248734,13.0000,F,S,test,1,Swane,George,Mr,F,F,None
1213,1214,NaN,2,male,26.0,0,0,244368,13.0000,F2,S,test,1,Nesson,Israel,Mr,F2,F2,None
618,619,1.0,2,female,4.0,2,1,230136,39.0000,F4,S,train,4,Becker,Marion Louise,Miss,F4,F4,None
516,517,1.0,2,female,34.0,0,0,CA 34260,10.5000,F33,S,train,1,Lemore,(Amelia Milley),Mrs,F33,F33,None
1217,1218,NaN,2,female,12.0,2,1,230136,39.0000,F4,S,test,4,Becker,Ruth Elizabeth,Miss,F4,F4,None
340,341,1.0,2,male,2.0,1,1,230080,26.0000,F2,S,train,3,Navratil,Edmond Roger,Master,F2,F2,None
193,194,1.0,2,male,3.0,1,1,230080,26.0000,F2,S,train,3,Navratil,Michel M,Master,F2,F2,None
183,184,1.0,2,male,1.0,2,1,230136,39.0000,F4,S,train,4,Becker,Richard F,Master,F4,F4,None
148,149,0.0,2,male,36.5,0,2,230080,26.0000,F2,S,train,3,Navratil,"Michel (""Louis M Hoffman"")",Mr,F2,F2,None
345,346,1.0,2,female,24.0,0,0,248733,13.0000,F33,S,train,1,Brown,"Amelia ""Mildred""",Miss,F33,F33,None
715,716,0.0,3,male,19.0,0,0,348124,7.6500,F G73,S,train,1,Soholt,Peter Andreas Lauritz Andersen,Mr,F G73,F,73
776,777,0.0,3,male,NaN,0,0,383121,7.7500,F38,Q,train,1,Tobin,Roger,Mr,F38,F38,None
948,949,NaN,3,male,25.0,0,0,348122,7.6500,F G63,S,test,1,Abelseth,Olaus Jorgensen,Mr,F G63,F,63
128,129,1.0,3,female,NaN,1,1,2668,22.3583,F E69,C,train,3,Peter,Anna,Miss,F E69,F E69,None
75,76,0.0,3,male,25.0,0,0,348123,7.6500,F G73,S,train,1,Moen,Sigurd Hansen,Mr,F G73,F,73
1179,1180,NaN,3,male,NaN,0,0,2655,7.2292,F E46,C,test,1,Mardirosian,Sarkis,Mr,F E46,F E46,None
1212,1213,NaN,3,male,25.0,0,0,2654,7.2292,F E57,C,test,1,Krekorian,Neshan,Mr,F E57,F E57,None
699,700,0.0,3,male,42.0,0,0,348121,7.6500,F G63,S,train,1,Humblen,Adolf Mathias Nicolai Olsen,Mr,F G63,F,63

In [50]:
df[(df.Cabin.str[0]=='G')]

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,source,Members,Last_name,First_name,Title,deck
10,11,1.0,3,female,4.0,1,1,PP 9549,16.7000,G6,S,train,3,Sandstrom,Marguerite Rut,Miss,G6
205,206,0.0,3,female,2.0,0,1,347054,10.4625,G6,S,train,2,Strom,Telma Matilda,Miss,G6
251,252,0.0,3,female,29.0,1,1,347054,10.4625,G6,S,train,3,Strom,Wilhelm (Elna Matilda Persson),Mrs,G6
394,395,1.0,3,female,24.0,0,2,PP 9549,16.7000,G6,S,train,3,Sandstrom,Hjalmar (Agnes Charlotta Bengtsson),Mrs,G6
1008,1009,NaN,3,female,1.0,1,1,PP 9549,16.7000,G6,S,test,3,Sandstrom,Beatrice Irene,Miss,G6

In [53]:
df[(df.Cabin.str[0]=='G')]['deck'].str.split(pat="G")

10      [, 6]
205     [, 6]
251     [, 6]
394     [, 6]
1008    [, 6]
Name: deck, dtype: object

In [54]:
df[['deck1','C1']] = df['deck'].str.split(pat="G", n=1, expand=True)

In [55]:
df[(df.Cabin.str[0]=='G')]

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,source,Members,Last_name,First_name,Title,deck,deck1,C1
10,11,1.0,3,female,4.0,1,1,PP 9549,16.7000,G6,S,train,3,Sandstrom,Marguerite Rut,Miss,G6,,6
205,206,0.0,3,female,2.0,0,1,347054,10.4625,G6,S,train,2,Strom,Telma Matilda,Miss,G6,,6
251,252,0.0,3,female,29.0,1,1,347054,10.4625,G6,S,train,3,Strom,Wilhelm (Elna Matilda Persson),Mrs,G6,,6
394,395,1.0,3,female,24.0,0,2,PP 9549,16.7000,G6,S,train,3,Sandstrom,Hjalmar (Agnes Charlotta Bengtsson),Mrs,G6,,6
1008,1009,NaN,3,female,1.0,1,1,PP 9549,16.7000,G6,S,test,3,Sandstrom,Beatrice Irene,Miss,G6,,6

In [ ]:
df.iloc[371]

In [ ]:
df['Cabin'].str.split(pat=",", n=1, expand=True)

In [ ]:
s.str.rsplit

In [64]:
df[(df.Cabin.str[0]=='F')].sort_values('Pclass',ascending=True)

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,source,Members,Last_name,First_name,Title,deck,deck1,C1
66,67,1.0,2,female,29.0,0,0,CA 2395,10.5000,F33,S,train,1,Nye,(Elizabeth Ramell),Mrs,F33,F33,None
1113,1114,NaN,2,female,22.0,0,0,W/C 14266,10.5000,F33,S,test,1,Cook,(Selena Rogers),Mrs,F33,F33,None
1069,1070,NaN,2,female,36.0,0,3,230136,39.0000,F4,S,test,4,Becker,Allen Oliver (Nellie E Baumgardner),Mrs,F4,F4,None
1000,1001,NaN,2,male,18.5,0,0,248734,13.0000,F,S,test,1,Swane,George,Mr,F,F,None
1213,1214,NaN,2,male,26.0,0,0,244368,13.0000,F2,S,test,1,Nesson,Israel,Mr,F2,F2,None
618,619,1.0,2,female,4.0,2,1,230136,39.0000,F4,S,train,4,Becker,Marion Louise,Miss,F4,F4,None
516,517,1.0,2,female,34.0,0,0,CA 34260,10.5000,F33,S,train,1,Lemore,(Amelia Milley),Mrs,F33,F33,None
1217,1218,NaN,2,female,12.0,2,1,230136,39.0000,F4,S,test,4,Becker,Ruth Elizabeth,Miss,F4,F4,None
340,341,1.0,2,male,2.0,1,1,230080,26.0000,F2,S,train,3,Navratil,Edmond Roger,Master,F2,F2,None
193,194,1.0,2,male,3.0,1,1,230080,26.0000,F2,S,train,3,Navratil,Michel M,Master,F2,F2,None
183,184,1.0,2,male,1.0,2,1,230136,39.0000,F4,S,train,4,Becker,Richard F,Master,F4,F4,None
148,149,0.0,2,male,36.5,0,2,230080,26.0000,F2,S,train,3,Navratil,"Michel (""Louis M Hoffman"")",Mr,F2,F2,None
345,346,1.0,2,female,24.0,0,0,248733,13.0000,F33,S,train,1,Brown,"Amelia ""Mildred""",Miss,F33,F33,None
715,716,0.0,3,male,19.0,0,0,348124,7.6500,F G73,S,train,1,Soholt,Peter Andreas Lauritz Andersen,Mr,F G73,F,73
776,777,0.0,3,male,NaN,0,0,383121,7.7500,F38,Q,train,1,Tobin,Roger,Mr,F38,F38,None
948,949,NaN,3,male,25.0,0,0,348122,7.6500,F G63,S,test,1,Abelseth,Olaus Jorgensen,Mr,F G63,F,63
128,129,1.0,3,female,NaN,1,1,2668,22.3583,F E69,C,train,3,Peter,Anna,Miss,F E69,F E69,None
75,76,0.0,3,male,25.0,0,0,348123,7.6500,F G73,S,train,1,Moen,Sigurd Hansen,Mr,F G73,F,73
1179,1180,NaN,3,male,NaN,0,0,2655,7.2292,F E46,C,test,1,Mardirosian,Sarkis,Mr,F E46,F E46,None
1212,1213,NaN,3,male,25.0,0,0,2654,7.2292,F E57,C,test,1,Krekorian,Neshan,Mr,F E57,F E57,None
699,700,0.0,3,male,42.0,0,0,348121,7.6500,F G63,S,train,1,Humblen,Adolf Mathias Nicolai Olsen,Mr,F G63,F,63

In [65]:
df[(df.Cabin.str[0]=='F')&(df.Pclass==3)].sort_values('Embarked',ascending=True)

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,source,Members,Last_name,First_name,Title,deck,deck1,C1
128,129,1.0,3,female,NaN,1,1,2668,22.3583,F E69,C,train,3,Peter,Anna,Miss,F E69,F E69,None
1179,1180,NaN,3,male,NaN,0,0,2655,7.2292,F E46,C,test,1,Mardirosian,Sarkis,Mr,F E46,F E46,None
1212,1213,NaN,3,male,25.0,0,0,2654,7.2292,F E57,C,test,1,Krekorian,Neshan,Mr,F E57,F E57,None
776,777,0.0,3,male,NaN,0,0,383121,7.7500,F38,Q,train,1,Tobin,Roger,Mr,F38,F38,None
75,76,0.0,3,male,25.0,0,0,348123,7.6500,F G73,S,train,1,Moen,Sigurd Hansen,Mr,F G73,F,73
699,700,0.0,3,male,42.0,0,0,348121,7.6500,F G63,S,train,1,Humblen,Adolf Mathias Nicolai Olsen,Mr,F G63,F,63
715,716,0.0,3,male,19.0,0,0,348124,7.6500,F G73,S,train,1,Soholt,Peter Andreas Lauritz Andersen,Mr,F G73,F,73
948,949,NaN,3,male,25.0,0,0,348122,7.6500,F G63,S,test,1,Abelseth,Olaus Jorgensen,Mr,F G63,F,63

In [ ]:
df[(df.Cabin.str[0]=='G')].sort_values('Ticket',ascending=True)

# We analyze  that Cabin Category are 'A','B','C','D','E','F','G'

In [ ]:
df[(df.Cabin.str[0]=='A')].sort_values('Cabin',ascending=False)

In [ ]:
df[(df.Cabin.isnull())&(df.Pclass==3)&((df.Fare<=23)&(df.Fare>=7.0000))].sort_values('Fare',ascending=True)

In [ ]:
df[(df.Cabin.isnull())&(df.Pclass==3)&((df.Ticket.str[0:2]=='34'))]

In [66]:
df.sort_values('Ticket',ascending=False)

      PassengerId  Survived  Pclass     Sex    Age  SibSp  Parch  \
745           746       0.0       1    male  70.00      1      1
540           541       1.0       1  female  36.00      0      2
905           906       NaN       1  female  47.00      1      0
92             93       0.0       1    male  46.00      1      0
235           236       0.0       3  female    NaN      0      0
147           148       0.0       3  female   9.00      2      2
86             87       0.0       3    male  16.00      1      3
736           737       0.0       3  female  48.00      1      3
436           437       0.0       3  female  21.00      2      2
1058         1059       NaN       3    male  18.00      2      2
924           925       NaN       3  female    NaN      1      2
783           784       0.0       3    male    NaN      1      2
1135         1136       NaN       3    male    NaN      1      2
888           889       0.0       3  female    NaN      1      2
1113         1114       NaN       2  female  22.00      0      0
242           243       0.0       2    male  29.00      0      0
1170         1171       NaN       2    male  22.00      0      0
526           527       1.0       2  female  50.00      0      0
219           220       0.0       2    male  30.00      0      0
570           571       1.0       2    male  62.00      0      0
226           227       1.0       2    male  19.00      0      0
1021         1022       NaN       3    male  32.00      0      0
115           116       0.0       3    male  21.00      0      0
382           383       0.0       3    male  32.00      0      0
636           637       0.0       3    male  32.00      0      0
936           937       NaN       3    male  25.00      0      0
816           817       0.0       3  female  23.00      0      0
400           401       1.0       3    male  39.00      0      0
744           745       1.0       3    male  31.00      0      0
579           580       1.0       3    male  32.00      0      0
664           665       1.0       3    male  20.00      1      0
216           217       1.0       3  female  27.00      0      0
2               3       1.0       3  female  26.00      0      0
173           174       0.0       3    male  21.00      0      0
142           143       1.0       3  female  24.00      1      0
403           404       0.0       3    male  28.00      1      0
243           244       0.0       3    male  22.00      0      0
433           434       0.0       3    male  17.00      0      0
590           591       0.0       3    male  35.00      0      0
729           730       0.0       3  female  25.00      1      0
909           910       NaN       3  female  27.00      1      0
414           415       1.0       3    male  44.00      0      0
988           989       NaN       3    male  29.00      0      0
67             68       0.0       3    male  19.00      0      0
157           158       0.0       3    male  30.00      0      0
220           221       1.0       3    male  16.00      0      0
564           565       0.0       3  female    NaN      0      0
87             88       0.0       3    male    NaN      0      0
1029         1030       NaN       3  female  23.00      0      0
563           564       0.0       3    male    NaN      0      0
429           430       1.0       3    male  32.00      0      0
884           885       0.0       3    male  25.00      0      0
491           492       0.0       3    male  21.00      0      0
511           512       0.0       3    male    NaN      0      0
1050         1051       NaN       3  female  26.00      0      2
1300         1301       NaN       3  female   3.00      1      1
1172         1173       NaN       3    male   0.75      1      1
1177         1178       NaN       3    male    NaN      0      0
784           785       0.0       3    male  25.00      0      0
210           211       0.0       3    male  24.00      0      0
363           364       0.0       3    male  35.00      0      0
1216         1217       NaN       3    male  23.00      0      0
1102         1103       NaN       3    male    NaN      0      0
131           132       0.0       3    male  20.00      0      0
465           466       0.0       3    male  38.00      0      0
611           612       0.0       3    male    NaN      0      0
933           934       NaN       3    male  41.00      0      0
1306         1307       NaN       3    male  38.50      0      0
840           841       0.0       3    male  20.00      0      0
1142         1143       NaN       3    male  20.00      0      0
761           762       0.0       3    male  41.00      0      0
150           151       0.0       2    male  51.00      0      0
1103         1104       NaN       2    male  17.00      0      0
120           121       0.0       2    male  21.00      2      0
665           666       0.0       2    male  32.00      2      0
655           656       0.0       2    male  24.00      2      0
72             73       0.0       2    male  21.00      0      0
1243         1244       NaN       2    male  18.00      0      0
385           386       0.0       2    male  18.00      0      0
1046         1047       NaN       3    male  24.00      0      0
648           649       0.0       3    male    NaN      0      0
772           773       0.0       2  female  57.00      0      0
841           842       0.0       2    male  16.00      0      0
1061         1062       NaN       3    male    NaN      0      0
1077         1078       NaN       2  female  21.00      0      1
1193         1194       NaN       2    male  43.00      0      1
84             85       1.0       2  female  17.00      0      0
239           240       0.0       2    male  33.00      0      0
945           946       NaN       2    male    NaN      0      0
473           474       1.0       2  female  23.00      0      0
921           922       NaN       2    male  50.00      1      0
432           433       1.0       2  female  42.00      1      0
1038         1039       NaN       3    male  22.00      0      0
1010         1011       NaN       2  female  29.00      1      0
594           595       0.0       2    male  37.00      1      0
942           943       NaN       2    male  27.00      0      0
906           907       NaN       2  female  24.00      1      0
361           362       0.0       2    male  29.00      1      0
1296         1297       NaN       2    male  20.00      0      0
292           293       0.0       2    male  36.00      0      0
1275         1276       NaN       2    male    NaN      0      0
866           867       1.0       2  female  27.00      1      0
1111         1112       NaN       2  female  30.00      1      0
1260         1261       NaN       2    male  29.00      0      0
547           548       1.0       2    male    NaN      0      0
135           136       0.0       2    male  23.00      0      0
181           182       0.0       2    male    NaN      0      0
608           609       1.0       2  female  22.00      1      2
1187         1188       NaN       2  female   1.00      1      2
685           686       0.0       2    male  25.00      1      2
43             44       1.0       2  female   3.00      1      2
827           828       1.0       2    male   1.00      0      2
817           818       0.0       2    male  31.00      1      1
1252         1253       NaN       2  female  24.00      1      1
45             46       0.0       3    male    NaN      0      0
389           390       1.0       2  female  17.00      0      0
1167         1168       NaN       2    male  28.00      0      0
1008         1009       NaN       3  female   1.00      1      1
10             11       1.0       3  female   4.00      1      1
394           395       1.0       3  female  24.00      0      2
225           226       0.0       3    male  22.00      0      0
544           545       0.0       1    male  50.00      1      0
537           538       1.0       1  female  30.00      0      0
1130         1131       NaN       1  female  48.00      1      0
325           326       1.0       1  female  36.00      0      0
269           270       1.0       1  female  35.00      0      0
1205         1206       NaN       1  female  55.00      0      0
373           374       0.0       1    male  22.00      0      0
1241         1242       NaN       1  female  45.00      0      1
97             98       1.0       1    male  23.00      0      1
505           506       0.0       1    male  18.00      1      0
1305         1306       NaN       1  female  39.00      0      0
307           308       1.0       1  female  17.00      1      0
380           381       1.0       1  female  42.00      0      0
1093         1094       NaN       1    male  47.00      1      0
716           717       1.0       1  female  38.00      0      0
557           558       0.0       1    male    NaN      0      0
700           701       1.0       1  female  18.00      1      0
1072         1073       NaN       1    male  37.00      1      1
835           836       1.0       1  female  39.00      1      1
1070         1071       NaN       1  female  64.00      0      2
737           738       1.0       1    male  35.00      0      0
679           680       1.0       1    male  36.00      0      1
1234         1235       NaN       1  female  58.00      0      1
258           259       1.0       1  female  35.00      0      0
96             97       0.0       1    male  71.00      0      0
1099         1100       NaN       1  female  33.00      0      0
295           296       0.0       1    male    NaN      0      0
660           661       1.0       1    male  50.00      2      0
334           335       1.0       1  female    NaN      1      0
194           195       1.0       1  female  44.00      0      0
493           494       0.0       1    male  71.00      0      0
742           743       1.0       1  female  21.00      2      2
950           951       NaN       1  female  36.00      0      0
311           312       1.0       1  female  18.00      2      2
1033         1034       NaN       1    male  61.00      1      3
955           956       NaN       1    male  13.00      2      2
915           916       NaN       1  female  48.00      1      3
1266         1267       NaN       1  female  45.00      0      0
1181         1182       NaN       1    male    NaN      0      0
1115         1116       NaN       1  female  53.00      0      0
64             65       0.0       1    male    NaN      0      0
34             35       0.0       1    male  28.00      1      0
375           376       1.0       1  female    NaN      1      0
513           514       1.0       1  female  54.00      1      0
911           912       NaN       1    male  55.00      1      0
30             31       0.0       1    male  40.00      0      0
793           794       0.0       1    male    NaN      0      0
1125         1126       NaN       1    male  39.00      1      0
1               2       1.0       1  female  38.00      1      0
913           914       NaN       1  female    NaN      0      0
914           915       NaN       1    male  21.00      0      1
155           156       0.0       1    male  51.00      0      1
273           274       0.0       1    male  37.00      0      1
177           178       0.0       1  female  50.00      0      0
937           938       NaN       1    male  45.00      0      0
139           140       0.0       1    male  24.00      0      0
789           790       0.0       1    male  46.00      0      0
853           854       1.0       1  female  16.00      0      1
1282         1283       NaN       1  female  51.00      0      1
1057         1058       NaN       1    male  48.00      0      0
867           868       0.0       1    male  31.00      0      0
1218         1219       NaN       1    male  46.00      0      0
256           257       1.0       1  female    NaN      0      0
268           269       1.0       1  female  58.00      0      1
609           610       1.0       1  female  40.00      0      0
332           333       0.0       1    male  38.00      0      1
1222         1223       NaN       1    male  39.00      0      0
645           646       1.0       1    male  48.00      1      0
681           682       1.0       1    male  27.00      0      0
52             53       1.0       1  female  49.00      1      0
1207         1208       NaN       1    male  57.00      1      0
31             32       1.0       1  female    NaN      1      0
195           196       1.0       1  female  58.00      0      0
964           965       NaN       1    male  28.50      0      0
299           300       1.0       1  female  50.00      0      1
1075         1076       NaN       1  female  27.00      1      1
118           119       0.0       1    male  24.00      0      1
1003         1004       NaN       1  female  36.00      0      0
309           310       1.0       1  female  30.00      0      0
599           600       1.0       1    male  49.00      1      0
972           973       NaN       1    male  67.00      1      0
527           528       0.0       1    male    NaN      0      0
1047         1048       NaN       1  female  29.00      0      0
1005         1006       NaN       1  female  63.00      1      0
710           711       1.0       1  female  24.00      0      0
641           642       1.0       1  female  24.00      0      0
369           370       1.0       1  female  24.00      0      0
707           708       1.0       1    male  42.00      0      0
701           702       1.0       1    male  35.00      0      0
572           573       1.0       1    male  36.00      0      0
512           513       1.0       1    male  36.00      0      0
168           169       0.0       1    male    NaN      0      0
874           875       1.0       2  female  28.00      1      0
308           309       0.0       2    male  30.00      1      0
1203         1204       NaN       3    male    NaN      0      0
597           598       0.0       3    male  49.00      0      0
179           180       0.0       3    male  36.00      0      0
271           272       1.0       3    male  25.00      0      0
302           303       0.0       3    male  19.00      0      0
1242         1243       NaN       2    male  25.00      0      0
956           957       NaN       2  female    NaN      0      0
1137         1138       NaN       2  female  22.00      0      0
458           459       1.0       2  female  50.00      0      0
314           315       0.0       2    male  43.00      1      1
440           441       1.0       2  female  45.00      1      1
535           536       1.0       2  female   7.00      0      2
1240         1241       NaN       2  female  31.00      0      0
211           212       1.0       2  female  35.00      0      0
1096         1097       NaN       1    male    NaN      0      0
983           984       NaN       1  female  27.00      1      2
671           672       0.0       1    male  31.00      1      0
154           155       0.0       3    male    NaN      0      0
883           884       0.0       2    male  28.00      0      0
497           498       0.0       3    male    NaN      0      0
1119         1120       NaN       3    male  40.50      0      0
845           846       0.0       3    male  42.00      0      0
1158         1159       NaN       3    male    NaN      0      0
1146         1147       NaN       3    male    NaN      0      0
348           349       1.0       3    male   3.00      1      1
940           941       NaN       3  female  36.00      0      2
489           490       1.0       3    male   9.00      1      1
1141         1142       NaN       2  female   0.92      1      2
58             59       1.0       2  female   5.00      1      2
450           451       0.0       2    male  36.00      1      2
472           473       1.0       2  female  33.00      1      2
1155         1156       NaN       2    male  30.00      0      0
516           517       1.0       2  female  34.00      0      0
1095         1096       NaN       2    male  25.00      0      0
161           162       1.0       2  female  40.00      0      0
1011         1012       NaN       2  female  12.00      0      0
549           550       1.0       2    male   8.00      1      1
145           146       0.0       2    male  19.00      1      1
1221         1222       NaN       2  female  48.00      0      2
1067         1068       NaN       2  female  20.00      0      0
70             71       0.0       2    male  32.00      0      0
637           638       0.0       2    male  31.00      1      1
237           238       1.0       2  female   8.00      0      2
801           802       1.0       2  female  31.00      1      1
1253         1254       NaN       2  female  31.00      0      0
1169         1170       NaN       2    male  30.00      1      0
1089         1090       NaN       2    male  23.00      0      0
922           923       NaN       2    male  24.00      2      0
1210         1211       NaN       2    male  22.00      2      0
1229         1230       NaN       2    male  25.00      0      0
56             57       1.0       2  female  21.00      0      0
1284         1285       NaN       2    male  47.00      0      0
746           747       0.0       3    male  16.00      1      1
279           280       1.0       3  female  35.00      1      1
1283         1284       NaN       3    male  13.00      0      2
672           673       0.0       2    male  70.00      0      0
33             34       0.0       2    male  66.00      0      0
234           235       0.0       2    male  24.00      0      0
846           847       0.0       3    male    NaN      8      2
201           202       0.0       3    male    NaN      8      2
863           864       0.0       3  female    NaN      8      2
159           160       0.0       3    male    NaN      8      2
324           325       0.0       3    male    NaN      8      2
1079         1080       NaN       3  female    NaN      8      2
1233         1234       NaN       3    male    NaN      1      9
180           181       0.0       3  female    NaN      8      2
1251         1252       NaN       3    male  14.50      8      2
792           793       0.0       3  female    NaN      8      2
1256         1257       NaN       3  female    NaN      1      9
66             67       1.0       2  female  29.00      0      0
134           135       0.0       2    male  25.00      0      0
93             94       0.0       3    male  26.00      1      2
923           924       NaN       3  female  33.00      1      2
788           789       1.0       3    male   1.00      1      2
1245         1246       NaN       3  female   0.17      1      2
678           679       0.0       3  female  43.00      1      6
1031         1032       NaN       3  female  10.00      5      2
1030         1031       NaN       3    male  40.00      1      6
480           481       0.0       3    male   9.00      5      2
71             72       0.0       3  female  16.00      5      2
683           684       0.0       3    male  14.00      5      2
59             60       0.0       3    male  11.00      5      2
386           387       0.0       3    male   1.00      5      2
649           650       1.0       3  female  23.00      0      0
439           440       0.0       2    male  31.00      0      0
265           266       0.0       2    male  36.00      0      0
1231         1232       NaN       2    male  18.00      0      0
376           377       1.0       3  female  22.00      0      0
365           366       0.0       3    male  30.00      0      0
818           819       0.0       3    male  43.00      0      0
508           509       0.0       3    male  28.00      0      0